version: '3'
services:
      client:
            restart: always
            build: ./client
            ports:
                  - "81:3001"
            depends_on:
                - api
            links:
                  - api
      api:
            container_name: server
            restart: always
            build: ./server
            ports:
                  - '4001:4001'
