version: '3'
services:
      client:
            restart: always
            build: ./client
            ports:
                  - "80:3000"
            depends_on:
                - api
            links:
                  - api
      api:
            container_name: backend
            restart: always
            build: ./server
            ports:
                  - '4000:4000'
